init_by_lua 'proxied_openai_base_url = os.getenv("NAT_CI_PROXIED_OPENAI_BASE_URL")';

server {
    listen                  8088;
    listen                  [::]:8088;
    server_name             _;

    resolver local=on;
    location / {

        set_by_lua $proxied_openai_base_url 'return proxied_openai_base_url';

        # Attempt to map the model name to the closest supported model
        access_by_lua_block {
            local model_name_map = {
                ["gpt-3.5-turbo"] = "azure/openai/gpt-4o-mini",
                ["gpt-4o"] = "azure/openai/gpt-4o-mini",
                ["gpt-4o-mini"] = "azure/openai/gpt-4o-mini",
                ["gpt-5"] = "us/azure/openai/gpt-5",
                ["gpt-5-mini"] = "openai/openai/gpt-5-mini",
                ["gpt-5-mini-2025-08-07"] = "openai/openai/gpt-5-mini",
                ["gpt-5-nano"] = "openai/openai/gpt-5-nano",
            }

            if ngx.req.get_method() ~= "POST" then
                return
            end
            ngx.req.read_body()
            local body = ngx.req.get_body_data()
            if not body or body == "" then
                return
            end
            local cjson = require "cjson"
            local ok, data = pcall(cjson.decode, body)
            if not ok or type(data) ~= "table" or not data.model then
                return
            end

            local original_model = data.model
            local new_model = model_name_map[data.model]
            if new_model == nil then
                ngx.log(ngx.ERR, "Requested model is not found: ", original_model)
                ngx.status = ngx.HTTP_NOT_FOUND
                ngx.header["Content-Type"] = "text/plain"
                ngx.say("requested model: " .. original_model .. " is not supported, to add support for this model, please update the nginx-rewrite-models service with the new model name")
                return ngx.exit(ngx.HTTP_NOT_FOUND)
            end
            data.model = new_model
            ngx.log(ngx.INFO, "New model: ", data.model)
            local new_payload = cjson.encode(data)
            ngx.req.set_body_data(new_payload)
        }

        proxy_pass $proxied_openai_base_url;
        proxy_ssl_server_name on;
        # Increase timeouts to 300 seconds (5 minutes)
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        proxy_set_header Authorization $http_authorization;
    }
}