# SPDX-FileCopyrightText: Copyright (c) 2025, Harbor Framework Contributors (https://github.com/harbor-framework/harbor)
# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Per-step metrics model for ATIF trajectories."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field


class Metrics(BaseModel):
    """LLM operational and confidence data for a single step."""

    prompt_tokens: int | None = Field(
        default=None,
        description="Total input tokens including cached and non-cached",
    )
    completion_tokens: int | None = Field(
        default=None,
        description="Total tokens generated by the LLM response",
    )
    cached_tokens: int | None = Field(
        default=None,
        description="Subset of prompt_tokens that were cache hits",
    )
    cost_usd: float | None = Field(
        default=None,
        description="Monetary cost of the API call in USD",
    )
    prompt_token_ids: list[int] | None = Field(
        default=None,
        description="Token IDs for prompt (input) tokens sent to the LLM, including chat history (if applicable)",
    )
    completion_token_ids: list[int] | None = Field(
        default=None,
        description="Token IDs for completion (response) tokens, enabling RL training without retokenization drift",
    )
    logprobs: list[float] | None = Field(
        default=None,
        description="Log probability assigned to each generated token",
    )
    extra: dict[str, Any] | None = Field(
        default=None,
        description="Other metrics (e.g. reasoning_tokens, cache_creation_input_tokens)",
    )

    model_config = ConfigDict(extra="forbid")
